#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseCareWeb.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="housecare")]
	public partial class housecareDBContextDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertaccount(account instance);
    partial void Updateaccount(account instance);
    partial void Deleteaccount(account instance);
    partial void InsertTuyendung(Tuyendung instance);
    partial void UpdateTuyendung(Tuyendung instance);
    partial void DeleteTuyendung(Tuyendung instance);
    partial void InsertCheckout(Checkout instance);
    partial void UpdateCheckout(Checkout instance);
    partial void DeleteCheckout(Checkout instance);
    partial void Insertchitietdichvu(chitietdichvu instance);
    partial void Updatechitietdichvu(chitietdichvu instance);
    partial void Deletechitietdichvu(chitietdichvu instance);
    partial void Insertdangkygoidichvu(dangkygoidichvu instance);
    partial void Updatedangkygoidichvu(dangkygoidichvu instance);
    partial void Deletedangkygoidichvu(dangkygoidichvu instance);
    partial void Insertdichvu(dichvu instance);
    partial void Updatedichvu(dichvu instance);
    partial void Deletedichvu(dichvu instance);
    partial void Insertgoidichvu(goidichvu instance);
    partial void Updategoidichvu(goidichvu instance);
    partial void Deletegoidichvu(goidichvu instance);
    partial void InsertLienhe(Lienhe instance);
    partial void UpdateLienhe(Lienhe instance);
    partial void DeleteLienhe(Lienhe instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void InsertPost(Post instance);
    partial void UpdatePost(Post instance);
    partial void DeletePost(Post instance);
    #endregion
		
		public housecareDBContextDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["housecareConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public housecareDBContextDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public housecareDBContextDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public housecareDBContextDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public housecareDBContextDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<account> accounts
		{
			get
			{
				return this.GetTable<account>();
			}
		}
		
		public System.Data.Linq.Table<Tuyendung> Tuyendungs
		{
			get
			{
				return this.GetTable<Tuyendung>();
			}
		}
		
		public System.Data.Linq.Table<Checkout> Checkouts
		{
			get
			{
				return this.GetTable<Checkout>();
			}
		}
		
		public System.Data.Linq.Table<chitietdichvu> chitietdichvus
		{
			get
			{
				return this.GetTable<chitietdichvu>();
			}
		}
		
		public System.Data.Linq.Table<dangkygoidichvu> dangkygoidichvus
		{
			get
			{
				return this.GetTable<dangkygoidichvu>();
			}
		}
		
		public System.Data.Linq.Table<dichvu> dichvus
		{
			get
			{
				return this.GetTable<dichvu>();
			}
		}
		
		public System.Data.Linq.Table<goidichvu> goidichvus
		{
			get
			{
				return this.GetTable<goidichvu>();
			}
		}
		
		public System.Data.Linq.Table<Lienhe> Lienhes
		{
			get
			{
				return this.GetTable<Lienhe>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<Post> Posts
		{
			get
			{
				return this.GetTable<Post>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FilterbyDate")]
		public ISingleResult<FilterbyDateResult> FilterbyDate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dateFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> dateTo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), dateFrom, dateTo);
			return ((ISingleResult<FilterbyDateResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.account")]
	public partial class account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Mataikhoan;
		
		private string _Taikhoan;
		
		private string _Email;
		
		private string _Matkhau;
		
		private string _Ten;
		
		private string _Sdt;
		
		private string _Quyen;
		
		private string _Img;
		
		private EntitySet<dangkygoidichvu> _dangkygoidichvus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMataikhoanChanging(string value);
    partial void OnMataikhoanChanged();
    partial void OnTaikhoanChanging(string value);
    partial void OnTaikhoanChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMatkhauChanging(string value);
    partial void OnMatkhauChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    #endregion
		
		public account()
		{
			this._dangkygoidichvus = new EntitySet<dangkygoidichvu>(new Action<dangkygoidichvu>(this.attach_dangkygoidichvus), new Action<dangkygoidichvu>(this.detach_dangkygoidichvus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mataikhoan", DbType="VarChar(50)")]
		public string Mataikhoan
		{
			get
			{
				return this._Mataikhoan;
			}
			set
			{
				if ((this._Mataikhoan != value))
				{
					this.OnMataikhoanChanging(value);
					this.SendPropertyChanging();
					this._Mataikhoan = value;
					this.SendPropertyChanged("Mataikhoan");
					this.OnMataikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan", DbType="VarChar(50)")]
		public string Taikhoan
		{
			get
			{
				return this._Taikhoan;
			}
			set
			{
				if ((this._Taikhoan != value))
				{
					this.OnTaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan = value;
					this.SendPropertyChanged("Taikhoan");
					this.OnTaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau", DbType="VarChar(50)")]
		public string Matkhau
		{
			get
			{
				return this._Matkhau;
			}
			set
			{
				if ((this._Matkhau != value))
				{
					this.OnMatkhauChanging(value);
					this.SendPropertyChanging();
					this._Matkhau = value;
					this.SendPropertyChanged("Matkhau");
					this.OnMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(50)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="VarChar(50)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="VarChar(50)")]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="VarChar(50)")]
		public string Img
		{
			get
			{
				return this._Img;
			}
			set
			{
				if ((this._Img != value))
				{
					this.OnImgChanging(value);
					this.SendPropertyChanging();
					this._Img = value;
					this.SendPropertyChanged("Img");
					this.OnImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="account_dangkygoidichvu", Storage="_dangkygoidichvus", ThisKey="Id", OtherKey="Idtaikhoan")]
		public EntitySet<dangkygoidichvu> dangkygoidichvus
		{
			get
			{
				return this._dangkygoidichvus;
			}
			set
			{
				this._dangkygoidichvus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dangkygoidichvus(dangkygoidichvu entity)
		{
			this.SendPropertyChanging();
			entity.account = this;
		}
		
		private void detach_dangkygoidichvus(dangkygoidichvu entity)
		{
			this.SendPropertyChanging();
			entity.account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tuyendung")]
	public partial class Tuyendung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.DateTime> _Ngaydangky;
		
		private string _Hoten;
		
		private string _Gioitinh;
		
		private string _Diachi;
		
		private string _Quequan;
		
		private string _Chucvu;
		
		private System.Nullable<int> _Tuoi;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _CCCD;
		
		private string _Sdt;
		
		private string _Kinhnghiem;
		
		private string _Email;
		
		private string _Mota;
		
		private string _Img;
		
		private System.Nullable<bool> _Trangthai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNgaydangkyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydangkyChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnQuequanChanging(string value);
    partial void OnQuequanChanged();
    partial void OnChucvuChanging(string value);
    partial void OnChucvuChanged();
    partial void OnTuoiChanging(System.Nullable<int> value);
    partial void OnTuoiChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnKinhnghiemChanging(string value);
    partial void OnKinhnghiemChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    partial void OnTrangthaiChanging(System.Nullable<bool> value);
    partial void OnTrangthaiChanged();
    #endregion
		
		public Tuyendung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydangky", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaydangky
		{
			get
			{
				return this._Ngaydangky;
			}
			set
			{
				if ((this._Ngaydangky != value))
				{
					this.OnNgaydangkyChanging(value);
					this.SendPropertyChanging();
					this._Ngaydangky = value;
					this.SendPropertyChanged("Ngaydangky");
					this.OnNgaydangkyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(50)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(MAX)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quequan", DbType="NVarChar(MAX)")]
		public string Quequan
		{
			get
			{
				return this._Quequan;
			}
			set
			{
				if ((this._Quequan != value))
				{
					this.OnQuequanChanging(value);
					this.SendPropertyChanging();
					this._Quequan = value;
					this.SendPropertyChanged("Quequan");
					this.OnQuequanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chucvu", DbType="NVarChar(50)")]
		public string Chucvu
		{
			get
			{
				return this._Chucvu;
			}
			set
			{
				if ((this._Chucvu != value))
				{
					this.OnChucvuChanging(value);
					this.SendPropertyChanging();
					this._Chucvu = value;
					this.SendPropertyChanged("Chucvu");
					this.OnChucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuoi", DbType="Int")]
		public System.Nullable<int> Tuoi
		{
			get
			{
				return this._Tuoi;
			}
			set
			{
				if ((this._Tuoi != value))
				{
					this.OnTuoiChanging(value);
					this.SendPropertyChanging();
					this._Tuoi = value;
					this.SendPropertyChanged("Tuoi");
					this.OnTuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(50)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="VarChar(10)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kinhnghiem", DbType="NVarChar(50)")]
		public string Kinhnghiem
		{
			get
			{
				return this._Kinhnghiem;
			}
			set
			{
				if ((this._Kinhnghiem != value))
				{
					this.OnKinhnghiemChanging(value);
					this.SendPropertyChanging();
					this._Kinhnghiem = value;
					this.SendPropertyChanged("Kinhnghiem");
					this.OnKinhnghiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="VarChar(50)")]
		public string Img
		{
			get
			{
				return this._Img;
			}
			set
			{
				if ((this._Img != value))
				{
					this.OnImgChanging(value);
					this.SendPropertyChanging();
					this._Img = value;
					this.SendPropertyChanged("Img");
					this.OnImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="Bit")]
		public System.Nullable<bool> Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Checkout")]
	public partial class Checkout : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Iddkdv;
		
		private System.Nullable<double> _Total;
		
		private EntityRef<dangkygoidichvu> _dangkygoidichvu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnIddkdvChanging(System.Nullable<int> value);
    partial void OnIddkdvChanged();
    partial void OnTotalChanging(System.Nullable<double> value);
    partial void OnTotalChanged();
    #endregion
		
		public Checkout()
		{
			this._dangkygoidichvu = default(EntityRef<dangkygoidichvu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Iddkdv", DbType="Int")]
		public System.Nullable<int> Iddkdv
		{
			get
			{
				return this._Iddkdv;
			}
			set
			{
				if ((this._Iddkdv != value))
				{
					if (this._dangkygoidichvu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIddkdvChanging(value);
					this.SendPropertyChanging();
					this._Iddkdv = value;
					this.SendPropertyChanged("Iddkdv");
					this.OnIddkdvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Float")]
		public System.Nullable<double> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dangkygoidichvu_Checkout", Storage="_dangkygoidichvu", ThisKey="Iddkdv", OtherKey="Id", IsForeignKey=true)]
		public dangkygoidichvu dangkygoidichvu
		{
			get
			{
				return this._dangkygoidichvu.Entity;
			}
			set
			{
				dangkygoidichvu previousValue = this._dangkygoidichvu.Entity;
				if (((previousValue != value) 
							|| (this._dangkygoidichvu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dangkygoidichvu.Entity = null;
						previousValue.Checkouts.Remove(this);
					}
					this._dangkygoidichvu.Entity = value;
					if ((value != null))
					{
						value.Checkouts.Add(this);
						this._Iddkdv = value.Id;
					}
					else
					{
						this._Iddkdv = default(Nullable<int>);
					}
					this.SendPropertyChanged("dangkygoidichvu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietdichvu")]
	public partial class chitietdichvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<int> _Madichvu;
		
		private System.Nullable<int> _Manhanvien;
		
		private EntityRef<dichvu> _dichvu;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMadichvuChanging(System.Nullable<int> value);
    partial void OnMadichvuChanged();
    partial void OnManhanvienChanging(System.Nullable<int> value);
    partial void OnManhanvienChanged();
    #endregion
		
		public chitietdichvu()
		{
			this._dichvu = default(EntityRef<dichvu>);
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madichvu", DbType="Int")]
		public System.Nullable<int> Madichvu
		{
			get
			{
				return this._Madichvu;
			}
			set
			{
				if ((this._Madichvu != value))
				{
					if (this._dichvu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMadichvuChanging(value);
					this.SendPropertyChanging();
					this._Madichvu = value;
					this.SendPropertyChanged("Madichvu");
					this.OnMadichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhanvien", DbType="Int")]
		public System.Nullable<int> Manhanvien
		{
			get
			{
				return this._Manhanvien;
			}
			set
			{
				if ((this._Manhanvien != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnManhanvienChanging(value);
					this.SendPropertyChanging();
					this._Manhanvien = value;
					this.SendPropertyChanged("Manhanvien");
					this.OnManhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dichvu_chitietdichvu", Storage="_dichvu", ThisKey="Madichvu", OtherKey="Id", IsForeignKey=true)]
		public dichvu dichvu
		{
			get
			{
				return this._dichvu.Entity;
			}
			set
			{
				dichvu previousValue = this._dichvu.Entity;
				if (((previousValue != value) 
							|| (this._dichvu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dichvu.Entity = null;
						previousValue.chitietdichvus.Remove(this);
					}
					this._dichvu.Entity = value;
					if ((value != null))
					{
						value.chitietdichvus.Add(this);
						this._Madichvu = value.Id;
					}
					else
					{
						this._Madichvu = default(Nullable<int>);
					}
					this.SendPropertyChanged("dichvu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_chitietdichvu", Storage="_nhanvien", ThisKey="Manhanvien", OtherKey="Id", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.chitietdichvus.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.chitietdichvus.Add(this);
						this._Manhanvien = value.Id;
					}
					else
					{
						this._Manhanvien = default(Nullable<int>);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dangkygoidichvu")]
	public partial class dangkygoidichvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Madangky;
		
		private System.Nullable<int> _Idtaikhoan;
		
		private System.Nullable<int> _Magoi;
		
		private System.Nullable<System.DateTime> _Ngaydangky;
		
		private string _Gio;
		
		private string _Diachi;
		
		private string _Yeucau;
		
		private System.Nullable<bool> _Trangthai;
		
		private System.Nullable<int> _Thoiluong;
		
		private System.Nullable<bool> _Active;
		
		private EntitySet<Checkout> _Checkouts;
		
		private EntityRef<account> _account;
		
		private EntityRef<goidichvu> _goidichvu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMadangkyChanging(string value);
    partial void OnMadangkyChanged();
    partial void OnIdtaikhoanChanging(System.Nullable<int> value);
    partial void OnIdtaikhoanChanged();
    partial void OnMagoiChanging(System.Nullable<int> value);
    partial void OnMagoiChanged();
    partial void OnNgaydangkyChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydangkyChanged();
    partial void OnGioChanging(string value);
    partial void OnGioChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnYeucauChanging(string value);
    partial void OnYeucauChanged();
    partial void OnTrangthaiChanging(System.Nullable<bool> value);
    partial void OnTrangthaiChanged();
    partial void OnThoiluongChanging(System.Nullable<int> value);
    partial void OnThoiluongChanged();
    partial void OnActiveChanging(System.Nullable<bool> value);
    partial void OnActiveChanged();
    #endregion
		
		public dangkygoidichvu()
		{
			this._Checkouts = new EntitySet<Checkout>(new Action<Checkout>(this.attach_Checkouts), new Action<Checkout>(this.detach_Checkouts));
			this._account = default(EntityRef<account>);
			this._goidichvu = default(EntityRef<goidichvu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madangky", DbType="VarChar(50)")]
		public string Madangky
		{
			get
			{
				return this._Madangky;
			}
			set
			{
				if ((this._Madangky != value))
				{
					this.OnMadangkyChanging(value);
					this.SendPropertyChanging();
					this._Madangky = value;
					this.SendPropertyChanged("Madangky");
					this.OnMadangkyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idtaikhoan", DbType="Int")]
		public System.Nullable<int> Idtaikhoan
		{
			get
			{
				return this._Idtaikhoan;
			}
			set
			{
				if ((this._Idtaikhoan != value))
				{
					if (this._account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdtaikhoanChanging(value);
					this.SendPropertyChanging();
					this._Idtaikhoan = value;
					this.SendPropertyChanged("Idtaikhoan");
					this.OnIdtaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Magoi", DbType="Int")]
		public System.Nullable<int> Magoi
		{
			get
			{
				return this._Magoi;
			}
			set
			{
				if ((this._Magoi != value))
				{
					if (this._goidichvu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMagoiChanging(value);
					this.SendPropertyChanging();
					this._Magoi = value;
					this.SendPropertyChanged("Magoi");
					this.OnMagoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydangky", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaydangky
		{
			get
			{
				return this._Ngaydangky;
			}
			set
			{
				if ((this._Ngaydangky != value))
				{
					this.OnNgaydangkyChanging(value);
					this.SendPropertyChanging();
					this._Ngaydangky = value;
					this.SendPropertyChanged("Ngaydangky");
					this.OnNgaydangkyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gio", DbType="NVarChar(MAX)")]
		public string Gio
		{
			get
			{
				return this._Gio;
			}
			set
			{
				if ((this._Gio != value))
				{
					this.OnGioChanging(value);
					this.SendPropertyChanging();
					this._Gio = value;
					this.SendPropertyChanged("Gio");
					this.OnGioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(MAX)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yeucau", DbType="NVarChar(MAX)")]
		public string Yeucau
		{
			get
			{
				return this._Yeucau;
			}
			set
			{
				if ((this._Yeucau != value))
				{
					this.OnYeucauChanging(value);
					this.SendPropertyChanging();
					this._Yeucau = value;
					this.SendPropertyChanged("Yeucau");
					this.OnYeucauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="Bit")]
		public System.Nullable<bool> Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoiluong", DbType="Int")]
		public System.Nullable<int> Thoiluong
		{
			get
			{
				return this._Thoiluong;
			}
			set
			{
				if ((this._Thoiluong != value))
				{
					this.OnThoiluongChanging(value);
					this.SendPropertyChanging();
					this._Thoiluong = value;
					this.SendPropertyChanged("Thoiluong");
					this.OnThoiluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this.OnActiveChanging(value);
					this.SendPropertyChanging();
					this._Active = value;
					this.SendPropertyChanged("Active");
					this.OnActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dangkygoidichvu_Checkout", Storage="_Checkouts", ThisKey="Id", OtherKey="Iddkdv")]
		public EntitySet<Checkout> Checkouts
		{
			get
			{
				return this._Checkouts;
			}
			set
			{
				this._Checkouts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="account_dangkygoidichvu", Storage="_account", ThisKey="Idtaikhoan", OtherKey="Id", IsForeignKey=true)]
		public account account
		{
			get
			{
				return this._account.Entity;
			}
			set
			{
				account previousValue = this._account.Entity;
				if (((previousValue != value) 
							|| (this._account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._account.Entity = null;
						previousValue.dangkygoidichvus.Remove(this);
					}
					this._account.Entity = value;
					if ((value != null))
					{
						value.dangkygoidichvus.Add(this);
						this._Idtaikhoan = value.Id;
					}
					else
					{
						this._Idtaikhoan = default(Nullable<int>);
					}
					this.SendPropertyChanged("account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="goidichvu_dangkygoidichvu", Storage="_goidichvu", ThisKey="Magoi", OtherKey="Id", IsForeignKey=true)]
		public goidichvu goidichvu
		{
			get
			{
				return this._goidichvu.Entity;
			}
			set
			{
				goidichvu previousValue = this._goidichvu.Entity;
				if (((previousValue != value) 
							|| (this._goidichvu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._goidichvu.Entity = null;
						previousValue.dangkygoidichvus.Remove(this);
					}
					this._goidichvu.Entity = value;
					if ((value != null))
					{
						value.dangkygoidichvus.Add(this);
						this._Magoi = value.Id;
					}
					else
					{
						this._Magoi = default(Nullable<int>);
					}
					this.SendPropertyChanged("goidichvu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Checkouts(Checkout entity)
		{
			this.SendPropertyChanging();
			entity.dangkygoidichvu = this;
		}
		
		private void detach_Checkouts(Checkout entity)
		{
			this.SendPropertyChanging();
			entity.dangkygoidichvu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dichvu")]
	public partial class dichvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Madichvu;
		
		private string _Tendichvu;
		
		private string _Img;
		
		private string _Mota;
		
		private EntitySet<chitietdichvu> _chitietdichvus;
		
		private EntitySet<goidichvu> _goidichvus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMadichvuChanging(string value);
    partial void OnMadichvuChanged();
    partial void OnTendichvuChanging(string value);
    partial void OnTendichvuChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    #endregion
		
		public dichvu()
		{
			this._chitietdichvus = new EntitySet<chitietdichvu>(new Action<chitietdichvu>(this.attach_chitietdichvus), new Action<chitietdichvu>(this.detach_chitietdichvus));
			this._goidichvus = new EntitySet<goidichvu>(new Action<goidichvu>(this.attach_goidichvus), new Action<goidichvu>(this.detach_goidichvus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madichvu", DbType="VarChar(50)")]
		public string Madichvu
		{
			get
			{
				return this._Madichvu;
			}
			set
			{
				if ((this._Madichvu != value))
				{
					this.OnMadichvuChanging(value);
					this.SendPropertyChanging();
					this._Madichvu = value;
					this.SendPropertyChanged("Madichvu");
					this.OnMadichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tendichvu", DbType="NVarChar(50)")]
		public string Tendichvu
		{
			get
			{
				return this._Tendichvu;
			}
			set
			{
				if ((this._Tendichvu != value))
				{
					this.OnTendichvuChanging(value);
					this.SendPropertyChanging();
					this._Tendichvu = value;
					this.SendPropertyChanged("Tendichvu");
					this.OnTendichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="VarChar(50)")]
		public string Img
		{
			get
			{
				return this._Img;
			}
			set
			{
				if ((this._Img != value))
				{
					this.OnImgChanging(value);
					this.SendPropertyChanging();
					this._Img = value;
					this.SendPropertyChanged("Img");
					this.OnImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dichvu_chitietdichvu", Storage="_chitietdichvus", ThisKey="Id", OtherKey="Madichvu")]
		public EntitySet<chitietdichvu> chitietdichvus
		{
			get
			{
				return this._chitietdichvus;
			}
			set
			{
				this._chitietdichvus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dichvu_goidichvu", Storage="_goidichvus", ThisKey="Id", OtherKey="Madichvu")]
		public EntitySet<goidichvu> goidichvus
		{
			get
			{
				return this._goidichvus;
			}
			set
			{
				this._goidichvus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdichvus(chitietdichvu entity)
		{
			this.SendPropertyChanging();
			entity.dichvu = this;
		}
		
		private void detach_chitietdichvus(chitietdichvu entity)
		{
			this.SendPropertyChanging();
			entity.dichvu = null;
		}
		
		private void attach_goidichvus(goidichvu entity)
		{
			this.SendPropertyChanging();
			entity.dichvu = this;
		}
		
		private void detach_goidichvus(goidichvu entity)
		{
			this.SendPropertyChanging();
			entity.dichvu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.goidichvu")]
	public partial class goidichvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Magoi;
		
		private string _Tengoi;
		
		private System.Nullable<double> _Giatien;
		
		private System.Nullable<int> _Madichvu;
		
		private string _Detail;
		
		private string _Loai;
		
		private EntitySet<dangkygoidichvu> _dangkygoidichvus;
		
		private EntityRef<dichvu> _dichvu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMagoiChanging(string value);
    partial void OnMagoiChanged();
    partial void OnTengoiChanging(string value);
    partial void OnTengoiChanged();
    partial void OnGiatienChanging(System.Nullable<double> value);
    partial void OnGiatienChanged();
    partial void OnMadichvuChanging(System.Nullable<int> value);
    partial void OnMadichvuChanged();
    partial void OnDetailChanging(string value);
    partial void OnDetailChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    #endregion
		
		public goidichvu()
		{
			this._dangkygoidichvus = new EntitySet<dangkygoidichvu>(new Action<dangkygoidichvu>(this.attach_dangkygoidichvus), new Action<dangkygoidichvu>(this.detach_dangkygoidichvus));
			this._dichvu = default(EntityRef<dichvu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Magoi", DbType="VarChar(50)")]
		public string Magoi
		{
			get
			{
				return this._Magoi;
			}
			set
			{
				if ((this._Magoi != value))
				{
					this.OnMagoiChanging(value);
					this.SendPropertyChanging();
					this._Magoi = value;
					this.SendPropertyChanged("Magoi");
					this.OnMagoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tengoi", DbType="NVarChar(50)")]
		public string Tengoi
		{
			get
			{
				return this._Tengoi;
			}
			set
			{
				if ((this._Tengoi != value))
				{
					this.OnTengoiChanging(value);
					this.SendPropertyChanging();
					this._Tengoi = value;
					this.SendPropertyChanged("Tengoi");
					this.OnTengoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giatien", DbType="Float")]
		public System.Nullable<double> Giatien
		{
			get
			{
				return this._Giatien;
			}
			set
			{
				if ((this._Giatien != value))
				{
					this.OnGiatienChanging(value);
					this.SendPropertyChanging();
					this._Giatien = value;
					this.SendPropertyChanged("Giatien");
					this.OnGiatienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madichvu", DbType="Int")]
		public System.Nullable<int> Madichvu
		{
			get
			{
				return this._Madichvu;
			}
			set
			{
				if ((this._Madichvu != value))
				{
					if (this._dichvu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMadichvuChanging(value);
					this.SendPropertyChanging();
					this._Madichvu = value;
					this.SendPropertyChanged("Madichvu");
					this.OnMadichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detail", DbType="NVarChar(MAX)")]
		public string Detail
		{
			get
			{
				return this._Detail;
			}
			set
			{
				if ((this._Detail != value))
				{
					this.OnDetailChanging(value);
					this.SendPropertyChanging();
					this._Detail = value;
					this.SendPropertyChanged("Detail");
					this.OnDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="NVarChar(50)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="goidichvu_dangkygoidichvu", Storage="_dangkygoidichvus", ThisKey="Id", OtherKey="Magoi")]
		public EntitySet<dangkygoidichvu> dangkygoidichvus
		{
			get
			{
				return this._dangkygoidichvus;
			}
			set
			{
				this._dangkygoidichvus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dichvu_goidichvu", Storage="_dichvu", ThisKey="Madichvu", OtherKey="Id", IsForeignKey=true)]
		public dichvu dichvu
		{
			get
			{
				return this._dichvu.Entity;
			}
			set
			{
				dichvu previousValue = this._dichvu.Entity;
				if (((previousValue != value) 
							|| (this._dichvu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dichvu.Entity = null;
						previousValue.goidichvus.Remove(this);
					}
					this._dichvu.Entity = value;
					if ((value != null))
					{
						value.goidichvus.Add(this);
						this._Madichvu = value.Id;
					}
					else
					{
						this._Madichvu = default(Nullable<int>);
					}
					this.SendPropertyChanged("dichvu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dangkygoidichvus(dangkygoidichvu entity)
		{
			this.SendPropertyChanging();
			entity.goidichvu = this;
		}
		
		private void detach_dangkygoidichvus(dangkygoidichvu entity)
		{
			this.SendPropertyChanging();
			entity.goidichvu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lienhe")]
	public partial class Lienhe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Hoten;
		
		private string _Email;
		
		private string _Sdt;
		
		private string _Diachi;
		
		private string _Ghichu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnGhichuChanging(string value);
    partial void OnGhichuChanged();
    #endregion
		
		public Lienhe()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="VarChar(50)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(50)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghichu", DbType="NVarChar(MAX)")]
		public string Ghichu
		{
			get
			{
				return this._Ghichu;
			}
			set
			{
				if ((this._Ghichu != value))
				{
					this.OnGhichuChanging(value);
					this.SendPropertyChanging();
					this._Ghichu = value;
					this.SendPropertyChanged("Ghichu");
					this.OnGhichuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Manhanvien;
		
		private string _Hoten;
		
		private string _Gioitinh;
		
		private string _Diachi;
		
		private string _Quequan;
		
		private string _Chucvu;
		
		private System.Nullable<int> _Tuoi;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _CCCD;
		
		private string _Sdt;
		
		private string _Kinhnghiem;
		
		private string _Email;
		
		private string _Mota;
		
		private string _Img;
		
		private EntitySet<chitietdichvu> _chitietdichvus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnManhanvienChanging(string value);
    partial void OnManhanvienChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    partial void OnGioitinhChanging(string value);
    partial void OnGioitinhChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnQuequanChanging(string value);
    partial void OnQuequanChanged();
    partial void OnChucvuChanging(string value);
    partial void OnChucvuChanged();
    partial void OnTuoiChanging(System.Nullable<int> value);
    partial void OnTuoiChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnCCCDChanging(string value);
    partial void OnCCCDChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnKinhnghiemChanging(string value);
    partial void OnKinhnghiemChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    #endregion
		
		public nhanvien()
		{
			this._chitietdichvus = new EntitySet<chitietdichvu>(new Action<chitietdichvu>(this.attach_chitietdichvus), new Action<chitietdichvu>(this.detach_chitietdichvus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manhanvien", DbType="VarChar(50)")]
		public string Manhanvien
		{
			get
			{
				return this._Manhanvien;
			}
			set
			{
				if ((this._Manhanvien != value))
				{
					this.OnManhanvienChanging(value);
					this.SendPropertyChanging();
					this._Manhanvien = value;
					this.SendPropertyChanged("Manhanvien");
					this.OnManhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gioitinh", DbType="NVarChar(50)")]
		public string Gioitinh
		{
			get
			{
				return this._Gioitinh;
			}
			set
			{
				if ((this._Gioitinh != value))
				{
					this.OnGioitinhChanging(value);
					this.SendPropertyChanging();
					this._Gioitinh = value;
					this.SendPropertyChanged("Gioitinh");
					this.OnGioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(MAX)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quequan", DbType="NVarChar(MAX)")]
		public string Quequan
		{
			get
			{
				return this._Quequan;
			}
			set
			{
				if ((this._Quequan != value))
				{
					this.OnQuequanChanging(value);
					this.SendPropertyChanging();
					this._Quequan = value;
					this.SendPropertyChanged("Quequan");
					this.OnQuequanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chucvu", DbType="NVarChar(50)")]
		public string Chucvu
		{
			get
			{
				return this._Chucvu;
			}
			set
			{
				if ((this._Chucvu != value))
				{
					this.OnChucvuChanging(value);
					this.SendPropertyChanging();
					this._Chucvu = value;
					this.SendPropertyChanged("Chucvu");
					this.OnChucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tuoi", DbType="Int")]
		public System.Nullable<int> Tuoi
		{
			get
			{
				return this._Tuoi;
			}
			set
			{
				if ((this._Tuoi != value))
				{
					this.OnTuoiChanging(value);
					this.SendPropertyChanging();
					this._Tuoi = value;
					this.SendPropertyChanged("Tuoi");
					this.OnTuoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCCD", DbType="VarChar(50)")]
		public string CCCD
		{
			get
			{
				return this._CCCD;
			}
			set
			{
				if ((this._CCCD != value))
				{
					this.OnCCCDChanging(value);
					this.SendPropertyChanging();
					this._CCCD = value;
					this.SendPropertyChanged("CCCD");
					this.OnCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="VarChar(10)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Kinhnghiem", DbType="NVarChar(50)")]
		public string Kinhnghiem
		{
			get
			{
				return this._Kinhnghiem;
			}
			set
			{
				if ((this._Kinhnghiem != value))
				{
					this.OnKinhnghiemChanging(value);
					this.SendPropertyChanging();
					this._Kinhnghiem = value;
					this.SendPropertyChanged("Kinhnghiem");
					this.OnKinhnghiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="VarChar(50)")]
		public string Img
		{
			get
			{
				return this._Img;
			}
			set
			{
				if ((this._Img != value))
				{
					this.OnImgChanging(value);
					this.SendPropertyChanging();
					this._Img = value;
					this.SendPropertyChanged("Img");
					this.OnImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_chitietdichvu", Storage="_chitietdichvus", ThisKey="Id", OtherKey="Manhanvien")]
		public EntitySet<chitietdichvu> chitietdichvus
		{
			get
			{
				return this._chitietdichvus;
			}
			set
			{
				this._chitietdichvus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdichvus(chitietdichvu entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_chitietdichvus(chitietdichvu entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Post")]
	public partial class Post : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Img;
		
		private string _Ngaydang;
		
		private string _Ten;
		
		private string _Mota;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnImgChanging(string value);
    partial void OnImgChanged();
    partial void OnNgaydangChanging(string value);
    partial void OnNgaydangChanged();
    partial void OnTenChanging(string value);
    partial void OnTenChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    #endregion
		
		public Post()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Img", DbType="VarChar(50)")]
		public string Img
		{
			get
			{
				return this._Img;
			}
			set
			{
				if ((this._Img != value))
				{
					this.OnImgChanging(value);
					this.SendPropertyChanging();
					this._Img = value;
					this.SendPropertyChanged("Img");
					this.OnImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydang", DbType="NVarChar(50)")]
		public string Ngaydang
		{
			get
			{
				return this._Ngaydang;
			}
			set
			{
				if ((this._Ngaydang != value))
				{
					this.OnNgaydangChanging(value);
					this.SendPropertyChanging();
					this._Ngaydang = value;
					this.SendPropertyChanged("Ngaydang");
					this.OnNgaydangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten", DbType="NVarChar(MAX)")]
		public string Ten
		{
			get
			{
				return this._Ten;
			}
			set
			{
				if ((this._Ten != value))
				{
					this.OnTenChanging(value);
					this.SendPropertyChanging();
					this._Ten = value;
					this.SendPropertyChanged("Ten");
					this.OnTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class FilterbyDateResult
	{
		
		private int _Id;
		
		private string _Madangky;
		
		private System.Nullable<int> _Idtaikhoan;
		
		private System.Nullable<int> _Magoi;
		
		private System.Nullable<System.DateTime> _Ngaydangky;
		
		private string _Gio;
		
		private string _Diachi;
		
		private string _Yeucau;
		
		private System.Nullable<bool> _Trangthai;
		
		private System.Nullable<int> _Thoiluong;
		
		private System.Nullable<bool> _Active;
		
		public FilterbyDateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madangky", DbType="VarChar(50)")]
		public string Madangky
		{
			get
			{
				return this._Madangky;
			}
			set
			{
				if ((this._Madangky != value))
				{
					this._Madangky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idtaikhoan", DbType="Int")]
		public System.Nullable<int> Idtaikhoan
		{
			get
			{
				return this._Idtaikhoan;
			}
			set
			{
				if ((this._Idtaikhoan != value))
				{
					this._Idtaikhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Magoi", DbType="Int")]
		public System.Nullable<int> Magoi
		{
			get
			{
				return this._Magoi;
			}
			set
			{
				if ((this._Magoi != value))
				{
					this._Magoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydangky", DbType="Date")]
		public System.Nullable<System.DateTime> Ngaydangky
		{
			get
			{
				return this._Ngaydangky;
			}
			set
			{
				if ((this._Ngaydangky != value))
				{
					this._Ngaydangky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gio", DbType="NVarChar(MAX)")]
		public string Gio
		{
			get
			{
				return this._Gio;
			}
			set
			{
				if ((this._Gio != value))
				{
					this._Gio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(MAX)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this._Diachi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yeucau", DbType="NVarChar(MAX)")]
		public string Yeucau
		{
			get
			{
				return this._Yeucau;
			}
			set
			{
				if ((this._Yeucau != value))
				{
					this._Yeucau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="Bit")]
		public System.Nullable<bool> Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this._Trangthai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoiluong", DbType="Int")]
		public System.Nullable<int> Thoiluong
		{
			get
			{
				return this._Thoiluong;
			}
			set
			{
				if ((this._Thoiluong != value))
				{
					this._Thoiluong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Bit")]
		public System.Nullable<bool> Active
		{
			get
			{
				return this._Active;
			}
			set
			{
				if ((this._Active != value))
				{
					this._Active = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
